### ISSUE TITLE
why WorkItemResultTWrapper<T>.Exception cast to T

### ISSUE THREAD

**Issue by GodZza** [amibar/SmartThreadPool#13]
when I try to use `IWorkItemResult.Exception`, I am get a `System.InvalidCastException`

exception detail:
```
InvalidCastException: Cannot cast from source type to destination type.
Amib.Threading.Internal.WorkItemResultTWrapper`1[System.String].get_Exception ()
```

and i looking the source code:
```
public object Exception
{
    get { return (TResult)_workItemResult.Exception; }
}
```

why the exception will be cast to TResult? is it a bug or feature

**Comment by amibar** [comment]
Fixed in commit  0286161
