### ISSUE TITLE
Support for .NET Core?

### ISSUE THREAD

**Issue by UweKeim** [amibar/SmartThreadPool#15]
Do you any plans to support your library running on [.NET Core](https://www.microsoft.com/net/core) in the near future?

**Comment by beufordy3k** [comment]
@amibar Are you taking pull requests for this?

**Comment by amibar** [comment]
@beufordy3k, you can create a pull request for this and I will merge it.
Thanks.

**Comment by espen75** [comment]
Do you have any plans to support your library running on .Net Core? Preferably .Net Core 2.0

**Comment by picadoh** [comment]
#17 might be of interest for this issue.
@amibar @UweKeim @beufordy3k @espen75

**Comment by 123g** [comment]
I've checked  NuGet and do not see SmartThreadPool.NetCore. Also, I downloaded the source code and do not see file SmartThreadPool.NetCore.csproj.

What am I missing.

Thanks
George

**Comment by 123g** [comment]
Found the link in case somebody else needs to download it
       https://github.com/picadoh/SmartThreadPool

You also need to read #17

**Comment by amibar** [comment]
@picadoh @UweKeim @beufordy3k @espen75 
I finally released a version that supports .NET core actually .NET Standard 2.0 and .NET Framework 4.6

**Comment by UweKeim** [comment]
Wow, this notification just came right in the moment when my build script fails with:

> Could not install package 'SmartThreadPool.dll 2.2.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

So I have to pin a previous NuGet version of SmartThreadPool to keep my .NET 4.5.2 program to still compile?

**Comment by amibar** [comment]
@UweKeim 
I just released another version with net40 and net45, please check it.

Thanks

**Comment by UweKeim** [comment]
Currently compiling. Looks promising right now, not yet finished, it is a rather large build script with douzens of SLNs and hundreds of CSPROJs.

Will post here if finished.

**Comment by UweKeim** [comment]
Compiles successfully now again. Thank you very much 👍

**Comment by amibar** [comment]
👍
