### ISSUE TITLE
Thread.Abort() is not supported in .NET Core

### ISSUE THREAD

**Issue by tedsmorris** [amibar/SmartThreadPool#19]
I'm looking at the updates to SmartThreadPool.NetCore.  Thread.Abort() is not supported in .NET Core, but I still see it in the .NET Core code?

**Comment by ashin-s** [comment]
I'm also facing the same issue while using .net core 3.0. Please advise.

**Comment by amibar** [comment]
See https://github.com/amibar/SmartThreadPool/issues/23

**Comment by mslissap** [comment]
Just wondering when this might be available. Thank you.

**Comment by g2david** [comment]
just changing abort to interrupt I guess

**Comment by amibar** [comment]
Solved in version 2.3.0, added .net core support
