### ISSUE TITLE
use SmartThreadPool app  crashed

### ISSUE THREAD

**Issue by Anonymous-ghost** [amibar/SmartThreadPool#21]
problem:
问题签名:
  问题事件名称:	BEX64
  应用程序名:	Run.exe
  应用程序版本:	2.0.0.0
  应用程序时间戳:	5d6dfe32
  故障模块名称:	StackHash_b4ee
  故障模块版本:	0.0.0.0
  故障模块时间戳:	00000000
  异常偏移:	000007fe00000000
  异常代码:	c0000005
  异常数据:	0000000000000008
  OS 版本:	6.1.7601.2.1.0.274.10
  区域设置 ID:	2052
  其他信息 1:	b4ee
  其他信息 2:	b4ee5de6a2322745523997a782b35692
  其他信息 3:	277e
  其他信息 4:	277e19c30fbd5f6bb531ec9e027c37c3

program info:
// 全局类型: <Module>
// 入口点: run.Main
// 架构: x64
// 运行库: .NET Framework 4.5.1
// 时间戳: 5DAD0D73 (2019/10/21 1:44:19)

SmartThreadPool.
// SmartThreadPool.dll

// 全局类型: <Module>
// 架构: AnyCPU (64位优先)
// 运行库: .NET Framework 4.5
// 时间戳: <未知> (83155524)

what can i do to sovle this problem
 thankyou

**Comment by Anonymous-ghost** [comment]
windows server 2008 r2 sp1  memery: 8G

**Comment by amibar** [comment]
Hi, I need at least a call stack of the relevant crash to understand what happened.
If you can please reconstruct the issue in code and add it here so I can take a look into it.

Ami

**Comment by Anonymous-ghost** [comment]
ok here is my code :

 private SmartThreadPool smartThreadPool = new SmartThreadPool();

 this.smartThreadPool.Name = "CMSThreadPool";//线程池的名字
            this.smartThreadPool.Concurrency = 100;//当前设置的最大支持线程数
            this.smartThreadPool.MinThreads = 15;//最小线程数,当没有工作项时,线程池最多剩余的线程数
            this.wig = this.smartThreadPool.CreateWorkItemsGroup(100);//200 代表任务组支持的线程数 创建了一个组
            this.smartThreadPool.Start();
            this.ScanThread = new Thread(new ThreadStart(this.Scan_cms));
            this.ScanThread.IsBackground = true;
            this.ScanThread.Start();
			
			
			 private void Scan_cms()   //开始扫描
        {
             
          
           

                for (int i = 0; i < this.works.Length; i++) //AllUrl.Length  works
                {
                    string str = this.works[i].ToString();
                   this.wig.QueueWorkItem(new WorkItemCallback(this.DoSomeWork), str);//把读取的一行创建新的线程到线程任务组中
                }
               
                this.IsScanActive = true; 
                
               
         

                
                


              
                
        }
		
		 private object DoSomeWork(object work)
        {
            // Do the work
            
           dowork(Convert.ToString(work));
            
            return null;
        }

public void dowork(string WebUrl)
        {
            
            try {
                for (int i = 0; i < this.cmsFinger.Length; i++) {
                    array2 = this.cmsFinger[i].Split(new char[]
				            {
					            '|'
				            });

                    urlFinger = array2[0].Trim(); //js/1.css
                    cmsName = array2[1].Trim(); //http://www.baidu.com
                    cmsFingerMd5 = array2[2].Trim().Trim();
                    url=WebUrl;
                    urlFingerMd = CmsGetMd5Finger.GetUrlFingerMd5StringArg(url+urlFinger);//获取指纹
                    if ("".Equals(urlFingerMd)) {
                        break;
                    } else if ("1".Equals(urlFingerMd)) {
                        continue;
                    } else {
						//get http://www.baidu.com  fineger
                        if (cmsFingerMd5.Equals(urlFingerMd) && cmsName.Equals("dedecms")) {  //finger succcess
                            cmsResult = DedeCms.dededowork(WebUrl); //get get result
                            if (!cmsResult.Contains("exp攻击失败!!!")) {
                                this.expAttackSucces++;  //count success number
                            }
                            
                           this.AddListViewData(WebUrl, cmsName, cmsResult);
                           
                            return;
                        }
                        
                    }
                }
            }
            catch {


            } finally {
                
               update process bar code
               

                
            }

        }
		
		public void AddListViewData(string string_8, string string_9, string string_10)  //add listview
        {
            
            if (!string.IsNullOrWhiteSpace(string_8))
            {
                WriteSuccessResult(string_8, string_9, string_10);
                ListViewItem listViewItem = new ListViewItem();
                listViewItem.Text = Convert.ToString(this.listView3.Items.Count + 1);
                listViewItem.SubItems.Add(string_8);
                listViewItem.SubItems.Add(string_9);
                listViewItem.SubItems.Add(string_10);
                this.listView3.Items.Add(listViewItem);
               

            }
           
        }

**Comment by amibar** [comment]
Hi,

It looks like you are accessing a UI control (this.listView3) from a thread of the SmartThreadPool. Windows only allows you to access the UI control from the UI thread, otherwise you get an exception something like: 
System.InvalidOperationException: Cross-thread operation not valid: Control '' accessed from a thread other than the thread it was created on.
that will crash the application if not handled.

If you are in WinForms project check InvokeRequired and then use BeginInvoke, see https://stackoverflow.com/questions/39513650/accessing-ui-from-outside-thread-in-winforms

Ami

**Comment by Anonymous-ghost** [comment]
ok  thank you  .is this code  don't work 
 public CmsForm()
        {
            this.InitializeComponent();
            Control.CheckForIllegalCrossThreadCalls = false;
}

**Comment by Anonymous-ghost** [comment]
i search the internet .most people said  this problem caused by microsoft Data Excution Protection 。I'm not sure

**Comment by amibar** [comment]
Don't disable the check, just work with the UI correctly. See the link I sent earlier.

**Comment by Anonymous-ghost** [comment]
ok i'll try the Delegates . all update UI  Must used the Delegates??? my soft has  windows forms such as label 。is this also used Delegates To update UI??
