### ISSUE TITLE
STP SmartThreadPool Thread# ThreadCounter > MaxThreads Settings

### ISSUE THREAD

**Issue by vnayak-mdsol** [amibar/SmartThreadPool#31]
Our **MaxThreads settings is set to 20**. However I see that the Thread Name [STP SmartThreadPool Thread#] increase over time and is currently at  ***STP SmartThreadPool Thread #62***  We've noticed this only in our test environments.

Can you please explain under what circumstances can the ThreadCounter number be greater than the MaxThreads settings?

**Comment by amibar** [comment]
Hi,

You are referrung to the name of the thread. 
Each thread is created with a name suffixed with an incrementing counter. 
Threads are created and terminated as time passes and the names are not reused, so you might have a thread named **Thread #1001**.
However, as long as the number of activate threads in an STP instance is not greater than the MaxThreads in the settings, you are ok.

Regards,
Ami

**Comment by vnayak-mdsol** [comment]
Thank you for clarifying.
