### ISSUE TITLE
Cancel(true) + WaitForIdle()

### ISSUE THREAD

**Issue by Olivier-Bastide-Numfem** [amibar/SmartThreadPool#34]
Hi Ami,

I'm having an issue and need your advice.
Code is very simple :
```
var pool = new SmartThreadPool(true);
items.ForEach(item => pool.QueueWorkItem(...));
try
{
	pool.Start();
	pool.WaitForIdle();
}
catch (ThreadAbortException)
{
	Thread.ResetAbort();
	pool.Cancel(true);
	pool.WaitForIdle();
}
```

In each working items, the ```Thread.Abort``` is handled to perform cleaning stuff.
What I want is, in case of cancellation, to wait for all threads in the pool to have this "cleaning stuff" done.
But the ```pool.WaitForIdle()``` in the ```catch``` doesn't seams to block, as there is some thread still alive doing their cleansing.

Is there a better/correct way to do this with your library ?
Thanks Ami !

**Comment by Vilo176** [comment]
Ok Ami, after some deeper investigations, I've pointed the problem.
Usage of Thread.Abort in my case is not good, because work item are using files, and aborting the thread causes file's handle not being disposed, hence my issues.
